persistence:
  username: ${DB_USERNAME:}
  password: ${DB_PASSWORD:}
  repository:
    url: ${RM_REPOSITORY_URL:http://localhost:7200/repositories/record-manager-app}
  formgen:
    url: ${FORMGEN_REPOSITORY_URL:http://localhost:7200/repositories/record-manager-formgen}
  driver: cz.cvut.kbss.ontodriver.rdf4j.Rdf4jDataSource

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI}
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI}